version: "3.7"

services:

  samba:
    image: dperson/samba # no hay tag con versiones, solo latest
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - TZ=America/Argentina/Mendoza
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads

  plex:
    image: lscr.io/linuxserver/plex:latest
    expose:
      - 32400
      - 33400
    # Descomentar si NO usas network_mode: "host"
    # ports:
    #  - 32400:32400
    #  - 33400:33400
    environment:
      - TZ=America/Argentina/Mendoza
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped
    network_mode: "host" # Solo funciona en Linux

  transmission:
    image : gists/transmission:4.0.3
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image: lscr.io/linuxserver/flexget:latest
    volumes:
      - ./flexget:/config
      - ./flexget/custom-cont-init.d:/custom-cont-init.d
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 5050:5050
    environment:
      - PUID=1001
      - PGID=1001
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=p3l4d0_N3RD # la puedes cambiar por la que quieras
    restart: unless-stopped

  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - 5800:5800
    volumes:
      - ./jdownloader-2:/config:rw
      - ${STORAGE}/torrents/complete:/output:rw
    restart: unless-stopped

  # jackett:
  #   image: lscr.io/linuxserver/jackett:latest
  #   container_name: jackett
  #   environment:
  #     - PUID=1001
  #     - PGID=115
  #     - TZ=Europe/Madrid
  #     - AUTO_UPDATE=false
  #   volumes:
  #     - /jackett:/config
  #     - ${STORAGE}/torrents:/downloads
  #   ports:
  #     - 9117:9117
  #   restart: unless-stopped

  # sonarr:
  #   image: lscr.io/linuxserver/sonarr:latest
  #   container_name: sonarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - /sonarr:/config
  #     - ${STORAGE}/torrents:/downloads
  #     # - /path/to/data:/config
  #     # - /path/to/tvseries:/tv #optional
  #     # - /path/to/downloadclient-downloads:/downloads #optional
  #   ports:
  #     - 8989:8989
  #   restart: unless-stopped